### ISSUE TITLE
aarch64 support of php-zendserver

### ISSUE THREAD

**Issue by anuscool** [zendtech/php-zendserver-docker#13]
i am trying to build php-zendserver on aarch64,does it supports on aarch64 platform?

**Comment by davidl-zend** [comment]
Unfortunately the underlying product Zend Server does not support aarch64. You can find the system requirements and supported operating systems in this page: http://files.zend.com/help/Zend-Server/content/system_requirements.htm

**Comment by anuscool** [comment]
if i have to add support of aarch64 for php-zendserver,how i will create packages zend-server-php-7.1=9.1.4+b170 on aarch64,is there any steps or document so that i can create php-zendserver on aarch64 using docker build through Dockerfile.

**Comment by davidl-zend** [comment]
Hi,

Zend Server is not open source you cannot build the zend-server-php-7.1=9.1.4+b170 deb package since you don't have the source.

Best regards,


David Lowes | Sr. Cloud Integration Engineer

Zend, a Rogue Wave company

Accelerating Great Code

P +972.3.753.9560 M +972.54.3000.810

www.zend.com / david.lowes@roguewave.com

________________________________

**Comment by anuscool** [comment]
Thanx for reply
we have requirement to build zend server for aarch64,do you have any suggestion for that?

**Comment by anuscool** [comment]
can you help me out to build php-zend-server for aarch64?
do you have any future plan for this?

**Comment by davidl-zend** [comment]
Hi,

Please contact me directly on my email:  david.lowes@roguewave.com and we'll schedule a call so I can better understand your needs.

Best regards,


David Lowes | Sr. Cloud Integration Engineer

Zend, a Rogue Wave company

Accelerating Great Code

P +972.3.753.9560 M +972.54.3000.810

www.zend.com / david.lowes@roguewave.com

________________________________
