### ISSUE TITLE
PHP 5.6 Zend 8.5 Docker image is not updated to use latest Dockerfile

### ISSUE THREAD

**Issue by asklokesh** [zendtech/php-zendserver-docker#15]
### The php-zendserver image tagged 8.5-php5.6 is still using base ubuntu 14.04 which is lagging changes to latest apache server capabilities and security patches. Please push the latest image from Master branch Dockerfile 

- Current Docker Image in reference: 5.6, 8.5-php5.6, 8.5 (8.5/5.6/Dockerfile) 
```
https://github.com/zendtech/php-zendserver-docker/blob/78105bf7c9123abbb432ddba50d73ecb482062ca/8.5/5.6/Dockerfile
```
VS
- Latest
```
https://github.com/zendtech/php-zendserver-docker/blob/master/8.5/5.6/Dockerfile
```

**Comment by andrus7k** [comment]
Please try zend/php-zendserver image, we are in proccess of releasing updated official images.

**Comment by asklokesh** [comment]
@andrus7k could you share the Dockerfile for `zend/php-zendserver:8.5-php5.6`

**Comment by andrus7k** [comment]
The official images also got updated.

**Comment by asklokesh** [comment]
Awesome. Thanks
