### ISSUE TITLE
Unable to start Zend Server cluster

### ISSUE THREAD

**Issue by ddovbii** [zendtech/php-zendserver-docker#2]
I have mysql container deployed on my machine. It works fine.
I'm trying to run zend server by following:

```
$ docker run -d -p 80:80 -p 10081:10081 -e MYSQL_HOSTNAME=172.17.0.8 -e MYSQL_PORT=3306 -e MYSQL_USERNAME=root -e MYSQL_PASSWORD=P@ssw0rd -e MYSQL_DBNAME=zend -e ZS_ADMIN_PASSWORD=P@ssw0rd --name=php4 php-zendserver
```

After that a container is created and works a few minutes.
Here are a logs:

```
Starting Zend Server 7.0.0 ..

Starting Zend Server Monitor node [OK]
[21.04.2015 08:38:38 SYSTEM] watchdog for monitor is running. 
[21.04.2015 08:38:38 SYSTEM] monitor is running. 
 * Starting web server apache2
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.10. Set the 'ServerName' directive globally to suppress this message
 * 
spawn-fcgi: child spawned successfully: PID: 146
Starting Zend Server GUI [Lighttpd] [OK]
[21.04.2015 08:38:41 SYSTEM] watchdog for lighttpd is running. 
[21.04.2015 08:38:41 SYSTEM] lighttpd is running. 
Starting Session Clustering daemon [OK]
[21.04.2015 08:38:42 SYSTEM] watchdog for scd is running. 
[21.04.2015 08:38:42 SYSTEM] scd is running. 
Starting Deployment [OK]
[21.04.2015 08:38:43 SYSTEM] watchdog for zdd is running. 
[21.04.2015 08:38:43 SYSTEM] zdd is running. 
Starting JobQueue [OK]
[21.04.2015 08:38:44 SYSTEM] watchdog for jqd is not running. 
[21.04.2015 08:38:44 SYSTEM] jqd is not running. 
Starting ZendServerDaemon [OK]
[21.04.2015 08:38:45 SYSTEM] watchdog for zsd is running. 
[21.04.2015 08:38:45 SYSTEM] zsd is running. 

Zend Server started...
Bootstrapping single server
Error: failed accessing Zend Server through the Web API
WebAPI error message : License key is invalid
WebAPI error code    : internalServerError
Joining cluster
Error: failed accessing Zend Server through the Web API
WebAPI error message : Failed retrieving server data for server a76b4bf07e47 - the server may have not been added to the cluster
WebAPI error code    : internalServerError
Error: authentication error. check your API key details
restarting Zend Server
Error: authentication error. check your API key details
Zend Server is ready for use
Your application is available at http://172.17.0.10
To access Zend Server, navigate to http://172.17.0.10:10081
Your admin password is P@ssw0rd
Usage:
/usr/local/bin/nothing <mysql-hostname> <mysql-port> <mysql-username> <mysql-password> <mysql-db-name> <server-id> <web-api-key-name> <web-api-key>
```

Please, help me

**Comment by ziniman** [comment]
Hi @ddovbii 

The problem looks like an expired Zend Server License. Since this Docker implementation is a preview, we include a time limited license with it. Looks like the you are using a version with a license that was expired in the last few days.

Please check the latest commit Dror did yesterday. It should include a license for the next few months. 

To specify a pre-purchased license use the following env vars:
ZEND_LICENSE_KEY
ZEND_LICENSE_ORDER

Please let us know if this fixed your issue.

Boaz.

**Comment by ddovbii** [comment]
Hi @ziniman
I'm using latest image of zend server. Do I understand correctly, that this image must include the correct license key?
I also tried put this key from commit to run command with -e ZEND_LICENSE_KEY. But I'm getting this problem anyway.

Let me to specify full way to stopping of container.

1. I use command:
$ docker run -d -p 80:80 -p 10081:10081 -e MYSQL_HOSTNAME=172.17.0.17 -e MYSQL_PORT=3306 -e MYSQL_USERNAME=root -e MYSQL_PASSWORD=P@ssw0rd -e MYSQL_DBNAME=zend -e ZS_ADMIN_PASSWORD=P@ssw0rd -e ZEND_LICENSE_KEY=B01G7J41801G21E2B016E4CCC2351803 --name=php6 php-zendserver

2. Container starts with logs:
Starting Zend Server 7.0.0 ..

Starting Zend Server Monitor node [OK]
[21.04.2015 11:33:57 SYSTEM] watchdog for monitor is running. 
[21.04.2015 11:33:57 SYSTEM] monitor is running. 
 * Starting web server apache2
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.18. Set the 'ServerName' directive globally to suppress this message
 * 
spawn-fcgi: child spawned successfully: PID: 147
Starting Zend Server GUI [Lighttpd] [OK]
[21.04.2015 11:34:01 SYSTEM] watchdog for lighttpd is running. 
[21.04.2015 11:34:01 SYSTEM] lighttpd is running. 
Starting Session Clustering daemon [OK]
[21.04.2015 11:34:02 SYSTEM] watchdog for scd is running. 
[21.04.2015 11:34:02 SYSTEM] scd is running. 
Starting Deployment [OK]
[21.04.2015 11:34:03 SYSTEM] watchdog for zdd is running. 
[21.04.2015 11:34:03 SYSTEM] zdd is running. 
Starting JobQueue [OK]
[21.04.2015 11:34:04 SYSTEM] watchdog for jqd is not running. 
[21.04.2015 11:34:04 SYSTEM] jqd is not running. 
Starting ZendServerDaemon [OK]
[21.04.2015 11:34:05 SYSTEM] watchdog for zsd is running. 
[21.04.2015 11:34:05 SYSTEM] zsd is running. 

Zend Server started...
Bootstrapping single server

3. I go to Zend Server UI using my browser. Here I am suggested to read License Agreement, to specify admin and developer password (btw, I specified ZS_ADMIN_PASSWORD in run command) , etc.

4. After I click "Launch" button, page hangs, container stops and I see updated logs: 

Starting Zend Server Monitor node [OK]
[21.04.2015 11:33:57 SYSTEM] watchdog for monitor is running. 
[21.04.2015 11:33:57 SYSTEM] monitor is running. 
 * Starting web server apache2
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.18. Set the 'ServerName' directive globally to suppress this message
 * 
spawn-fcgi: child spawned successfully: PID: 147
Starting Zend Server GUI [Lighttpd] [OK]
[21.04.2015 11:34:01 SYSTEM] watchdog for lighttpd is running. 
[21.04.2015 11:34:01 SYSTEM] lighttpd is running. 
Starting Session Clustering daemon [OK]
[21.04.2015 11:34:02 SYSTEM] watchdog for scd is running. 
[21.04.2015 11:34:02 SYSTEM] scd is running. 
Starting Deployment [OK]
[21.04.2015 11:34:03 SYSTEM] watchdog for zdd is running. 
[21.04.2015 11:34:03 SYSTEM] zdd is running. 
Starting JobQueue [OK]
[21.04.2015 11:34:04 SYSTEM] watchdog for jqd is not running. 
[21.04.2015 11:34:04 SYSTEM] jqd is not running. 
Starting ZendServerDaemon [OK]
[21.04.2015 11:34:05 SYSTEM] watchdog for zsd is running. 
[21.04.2015 11:34:05 SYSTEM] zsd is running. 

Zend Server started...
Bootstrapping single server
Error: failed accessing Zend Server through the Web API
WebAPI error message : License key is invalid
WebAPI error code    : internalServerError
Joining cluster
Error: failed accessing Zend Server through the Web API
WebAPI error message : Failed retrieving server data for server 6d28c29d8f97 - the server may have not been added to the cluster
WebAPI error code    : internalServerError
Error: authentication error. check your API key details
restarting Zend Server
Error: authentication error. check your API key details
Zend Server is ready for use
Your application is available at http://172.17.0.18
To access Zend Server, navigate to http://172.17.0.18:10081
Your admin password is P@ssw0rd
Usage:
/usr/local/bin/nothing <mysql-hostname> <mysql-port> <mysql-username> <mysql-password> <mysql-db-name> <server-id> <web-api-key-name> <web-api-key>

I hope this more detailed info helps you to help me =)

Thanks,
Dmytro

**Comment by dror-g** [comment]
Hi Dmytro,
The problem in this case was the pasword string - P@ssw0rd.
I believe the "@" character caused some problems to docker / the init scripts.

Also, when specifying a license as Boaz suggested, you should include both ZEND_LICENSE_KEY and ZEND_LICENSE_ORDER env variables. one will not do.

 sorry for the late response, please let us know if this resolved the issue for you!
Dror.

**Comment by davidl-zend** [comment]
No response for some time.
